### ISSUE TITLE
Memory usage not showing

### ISSUE THREAD

**Issue by fpvandoorn** [seripap/vscode-memory#15]
```
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

(partial) Extension Host output:
```
2023-06-21 18:29:27.011 [info] ExtensionService#_doActivateExtension seripap.vscode-memory, startup: false, activationEvent: '*'
2023-06-21 18:30:04.798 [info] Extension host terminating: renderer closed the MessagePort
2023-06-21 18:30:04.811 [error] Canceled: Canceled
	at new l (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:105905)
	at s.O (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11754)
	at $.<computed>.j.charCodeAt.$.<computed> (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9029)
	at e.ExtHostCommands.g (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130078)
	at e.ExtHostCommands.executeCommand (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129454)
	at k.registerCommand.description (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:128747)
	at e.ExtHostCommands.h (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130664)
	at e.ExtHostCommands.g (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129554)
	at e.ExtHostCommands.executeCommand (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129454)
	at Object.executeCommand (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:24230)
	at D (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1261288)
	at b.invoke (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at d.deliver (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at n.fire (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at Object.m [as dispose] (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1276121)
	at c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280622
	at Array.forEach (<anonymous>)
	at g.dispose (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280608)
	at r.<anonymous> (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12552)
	at r.dispose (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12687)
	at r.<anonymous> (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1263418)
	at r.dispose (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12687)
	at I (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12083)
	at n.Z (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:11285)
	at c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9187
	at Array.map (<anonymous>)
	at n.S (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9175)
	at n.terminate (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9445)
	at h.terminate (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1544)
	at p (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:34497)
	at MessagePortMain.<anonymous> (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30636)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-06-21 18:30:04.814 [error] Canceled: Canceled
	at new l (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:105905)
	at s.O (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11754)
	at $.<computed>.j.charCodeAt.$.<computed> (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9029)
	at e.ExtHostCommands.g (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130078)
	at e.ExtHostCommands.executeCommand (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129454)
	at k.registerCommand.description (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:128747)
	at e.ExtHostCommands.h (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130664)
	at e.ExtHostCommands.g (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129554)
	at e.ExtHostCommands.executeCommand (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129454)
	at Object.executeCommand (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:24230)
	at set b [as b] (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:152873)
	at c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:153583
	at c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1348881
	at b.invoke (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at d.deliver (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at n.fire (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at Object.m [as dispose] (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1276121)
	at c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280622
	at Array.forEach (<anonymous>)
	at g.dispose (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280608)
	at r.<anonymous> (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12552)
	at r.dispose (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12687)
	at r.<anonymous> (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1263418)
	at r.dispose (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12687)
	at I (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12083)
	at n.Z (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:11285)
	at c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9187
	at Array.map (<anonymous>)
	at n.S (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9175)
	at n.terminate (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9445)
	at h.terminate (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1544)
	at p (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:34497)
	at MessagePortMain.<anonymous> (c:\Users\Floris\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30636)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-06-21 18:30:04.822 [info] Extension host with pid 30564 exiting with code 0
2023-06-21 18:30:05.611 [info] Extension host with pid 29272 started
```

**Comment by fpvandoorn** [comment]
Oh, I'm not sure if this error is caused by this extension. I seem to get the same error after disabling this extension...
